In [1]:

from array import *

array1 = array('i', [10,20,30,40,50])

for x in array1:
   print(x)

10
20
30
40
50


In [2]:
# for accessing the element
from array import *

array1 = array('i', [10,20,30,40,50])

print (array1[0])

print (array1[2])

10
30


In [ ]:
# Insertion Operation
from array import *

array1 = array('i', [10,20,30,40,50])

array1.insert(1,60)

for x in array1:
   print(x)

In [4]:
# Deletion Operation
from array import *
array = array('i', [10,20,30,40,50])
array1.remove(10)
for x in array1:
    print(x)
    

20
30
40
50


In [9]:
# Search Operation
from array import *
array1 = array('i', [10,20,30,40,50])
print(array1.index(50))
    


4


In [11]:
# Update Operation
from array import *
array1 = array('i', [10,20,30,40,50])
array1[2] = 80
for x in array1:
    print(x)
    


10
20
80
40
50


In [12]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

print(T[0])

print(T[1][2])

[11, 12, 5, 2]
10


In [13]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]
for r in T:
   for c in r:
      print(c,end = " ")
   print()

11 12 5 2 
15 6 10 
10 8 12 5 
12 15 8 6 


In [14]:
from array import *
T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

T.insert(2, [0,5,11,13,6])

for r in T:
   for c in r:
      print(c,end = " ")
   print()

11 12 5 2 
15 6 10 
0 5 11 13 6 
10 8 12 5 
12 15 8 6 


In [ ]:

from numpy import *
# array in 2D
a = array([['mon', 3, 4, 5, 6],['tue', 5,6,7,8,],['wed', 2,3,4,5,],
               ['thirs', 3, 4, 5, 6],['fri', 5,6,7,8,],['sat', 2,3,4,5,]
               ['sun', 3, 4, 5, 6]])
m = reshape(a, (7,5))
print(m)

In [19]:
# ARRAY IN 2D
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = reshape(a,(7,5))
print(m)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['Wed' '15' '21' '20' '19']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']]


In [27]:

from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
print(m[2])
print(m[0][2])

['Wed' '15' '21' '20' '19']
20


In [33]:

from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = append(a,[[ 'jan',11,2,33,44,]],0)
print(m)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['Wed' '15' '21' '20' '19']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']
 ['jan' '11' '2' '33' '44']]


In [37]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = insert(a,[5],[[11],[2],[33],[44],[23],[43],[78]],1)
print(m)

[['Mon' '18' '20' '22' '17' '11']
 ['Tue' '11' '18' '21' '18' '2']
 ['Wed' '15' '21' '20' '19' '33']
 ['Thu' '11' '20' '22' '21' '44']
 ['Fri' '18' '17' '23' '22' '23']
 ['Sat' '12' '22' '20' '18' '43']
 ['Sun' '13' '15' '19' '16' '78']]


In [42]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = delete(a,[2],1)
print(m)

[['Mon' '18' '22' '17']
 ['Tue' '11' '21' '18']
 ['Wed' '15' '20' '19']
 ['Thu' '11' '22' '21']
 ['Fri' '18' '23' '22']
 ['Sat' '12' '20' '18']
 ['Sun' '13' '19' '16']]


In [45]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
a[2] = ['jan',1,2,3,45]
print(a)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['jan' '1' '2' '3' '45']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']]


In [46]:
# two matrix addintion
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 + matrix2

print(result)



[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [47]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 * matrix2

print(result)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [48]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 - matrix2

print(result)


[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [1]:
# class
class car:  
    def __init__(self,modelname, year):  
        self.modelname = modelname  
        self.year = year  
    def display(self):  
        print(self.modelname,self.year)  
  
c1 = car("Toyota", 2016)  
c1.display()  

Toyota 2016


In [4]:
class Person:  
    def __init__(self, name, age):  
        # This is the constructor method that is called when creating a new Person object  
        # It takes two parameters, name and age, and initializes them as attributes of the object  
        self.name = name  
        self.age = age  
    def greet(self):  
        # This is a method of the Person class that prints a greeting message  
        print("Hello, my name is " + self.name)  

In [5]:
class Person:  
    def __init__(self, name, age):  
        self.name = name    
        self.age = age      
    def greet(self):  
        print("Hello, my name is " + self.name)  
  
# Create a new instance of the Person class and assign it to the variable person1  
person1 = Person("Ayan", 25)  
person1.greet()    

Hello, my name is Ayan


In [6]:
class Person:  
    count = 0   # This is a class variable  
  
    def __init__(self, name, age):  
        self.name = name    # This is an instance variable  
        self.age = age  
        Person.count += 1   # Accessing the class variable using the name of the class  
person1 = Person("Ayan", 25)  
person2 = Person("Bobby", 30)  
print(Person.count)     


2


In [7]:
class Person:  
    def __init__(self, name, age):  
        self.name = name    # This is an instance variable  
        self.age = age  
person1 = Person("Ayan", 25)  
person2 = Person("Bobby", 30)  
print(person1.name)    
print(person2.age)     

Ayan
30


In [8]:
class Employee:  
    def __init__(self, name, id):  
        self.id = id  
        self.name = name  
  
    def display(self):  
        print("ID: %d \nName: %s" % (self.id, self.name))  
  
  
emp1 = Employee("John", 101)  
emp2 = Employee("David", 102)  
  
# accessing display() method to print employee 1 information  
  
emp1.display()  
  
# accessing display() method to print employee 2 information  
emp2.display()  

ID: 101 
Name: John
ID: 102 
Name: David


In [9]:
class Student:    
    count = 0    
    def __init__(self):    
        Student.count = Student.count + 1    
s1=Student()    
s2=Student()    
s3=Student()    
print("The number of students:",Student.count)    

The number of students: 3


In [10]:
class Student:  
    # Constructor - non parameterized  
    def __init__(self):  
        print("This is non parametrized constructor")  
    def show(self,name):  
        print("Hello",name)  
student = Student()  
student.show("John")      

This is non parametrized constructor
Hello John


In [11]:
class Student:  
    # Constructor - parameterized  
    def __init__(self, name):  
        print("This is parametrized constructor")  
        self.name = name  
    def show(self):  
        print("Hello",self.name)  
student = Student("John")  
student.show()    

This is parametrized constructor
Hello John


In [12]:
class Student:  
    roll_num = 101  
    name = "Joseph"  
  
    def display(self):  
        print(self.roll_num,self.name)  
  
st = Student()  
st.display()  

101 Joseph


In [13]:
class Student:  
    def __init__(self):  
        print("The First Constructor")  
    def __init__(self):  
        print("The second contructor")  
  
st = Student()  

The second contructor


In [14]:
class Student:  
    def __init__(self, name, id, age):  
        self.name = name  
        self.id = id  
        self.age = age  
  
    # creates the object of the class Student  
s = Student("John", 101, 22)  
  
# prints the attribute name of the object s  
print(getattr(s, 'name'))  
  
# reset the value of attribute age to 23  
setattr(s, "age", 23)  
  
# prints the modified value of age  
print(getattr(s, 'age'))  
  
# prints true if the student contains the attribute with name id  
  
print(hasattr(s, 'id'))  
# deletes the attribute age  
delattr(s, 'age')  
  
# this will give an error since the attribute age has been deleted  
print(s.age)  

John
23
True


AttributeError: 'Student' object has no attribute 'age'

In [15]:
class Student:    
    def __init__(self,name,id,age):    
        self.name = name;    
        self.id = id;    
        self.age = age    
    def display_details(self):    
        print("Name:%s, ID:%d, age:%d"%(self.name,self.id))    
s = Student("John",101,22)    
print(s.__doc__)    
print(s.__dict__)    
print(s.__module__)    

None
{'name': 'John', 'id': 101, 'age': 22}
__main__
