In [1]:

from array import *

array1 = array('i', [10,20,30,40,50])

for x in array1:
   print(x)

10
20
30
40
50


In [2]:
# for accessing the element
from array import *

array1 = array('i', [10,20,30,40,50])

print (array1[0])

print (array1[2])

10
30


In [ ]:
# Insertion Operation
from array import *

array1 = array('i', [10,20,30,40,50])

array1.insert(1,60)

for x in array1:
   print(x)

In [4]:
# Deletion Operation
from array import *
array = array('i', [10,20,30,40,50])
array1.remove(10)
for x in array1:
    print(x)
    

20
30
40
50


In [9]:
# Search Operation
from array import *
array1 = array('i', [10,20,30,40,50])
print(array1.index(50))
    


4


In [11]:
# Update Operation
from array import *
array1 = array('i', [10,20,30,40,50])
array1[2] = 80
for x in array1:
    print(x)
    


10
20
80
40
50


In [12]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

print(T[0])

print(T[1][2])

[11, 12, 5, 2]
10


In [13]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]
for r in T:
   for c in r:
      print(c,end = " ")
   print()

11 12 5 2 
15 6 10 
10 8 12 5 
12 15 8 6 


In [14]:
from array import *
T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

T.insert(2, [0,5,11,13,6])

for r in T:
   for c in r:
      print(c,end = " ")
   print()

11 12 5 2 
15 6 10 
0 5 11 13 6 
10 8 12 5 
12 15 8 6 


In [ ]:

from numpy import *
# array in 2D
a = array([['mon', 3, 4, 5, 6],['tue', 5,6,7,8,],['wed', 2,3,4,5,],
               ['thirs', 3, 4, 5, 6],['fri', 5,6,7,8,],['sat', 2,3,4,5,]
               ['sun', 3, 4, 5, 6]])
m = reshape(a, (7,5))
print(m)

In [19]:
# ARRAY IN 2D
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = reshape(a,(7,5))
print(m)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['Wed' '15' '21' '20' '19']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']]


In [27]:

from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
print(m[2])
print(m[0][2])

['Wed' '15' '21' '20' '19']
20


In [33]:

from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = append(a,[[ 'jan',11,2,33,44,]],0)
print(m)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['Wed' '15' '21' '20' '19']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']
 ['jan' '11' '2' '33' '44']]


In [37]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = insert(a,[5],[[11],[2],[33],[44],[23],[43],[78]],1)
print(m)

[['Mon' '18' '20' '22' '17' '11']
 ['Tue' '11' '18' '21' '18' '2']
 ['Wed' '15' '21' '20' '19' '33']
 ['Thu' '11' '20' '22' '21' '44']
 ['Fri' '18' '17' '23' '22' '23']
 ['Sat' '12' '22' '20' '18' '43']
 ['Sun' '13' '15' '19' '16' '78']]


In [42]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
m = delete(a,[2],1)
print(m)

[['Mon' '18' '22' '17']
 ['Tue' '11' '21' '18']
 ['Wed' '15' '20' '19']
 ['Thu' '11' '22' '21']
 ['Fri' '18' '23' '22']
 ['Sat' '12' '20' '18']
 ['Sun' '13' '19' '16']]


In [45]:
from numpy import * 
a = array([['Mon',18,20,22,17],['Tue',11,18,21,18],
   ['Wed',15,21,20,19],['Thu',11,20,22,21],
   ['Fri',18,17,23,22],['Sat',12,22,20,18],
   ['Sun',13,15,19,16]])
a[2] = ['jan',1,2,3,45]
print(a)

[['Mon' '18' '20' '22' '17']
 ['Tue' '11' '18' '21' '18']
 ['jan' '1' '2' '3' '45']
 ['Thu' '11' '20' '22' '21']
 ['Fri' '18' '17' '23' '22']
 ['Sat' '12' '22' '20' '18']
 ['Sun' '13' '15' '19' '16']]


In [46]:
# two matrix addintion
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 + matrix2

print(result)



[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [47]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 * matrix2

print(result)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [48]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = matrix1 - matrix2

print(result)


[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
