Write a NumPy program to create an array of 10 zeros.

In [1]:
import numpy as np
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Write a NumPy program to create an array of 10 ones

In [2]:
import numpy as np
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8

In [4]:
import numpy as np
range = np.arange(9)
mat = range.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Write a NumPy program to reverse an array (first element becomes the last)

In [5]:
import numpy as np
num = np.array([1,2,3,4,5,6,7])
print(num[::-1])

[7 6 5 4 3 2 1]


Write a NumPy program to extract all odd numbers from an array.

In [8]:
import numpy as np
num = np.array([1,2,3,4,5,6,7])
odd = num[num%2==1]
print(odd)


[1 3 5 7]


Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array

In [11]:
import numpy as np
num = np.array([1,2,3,4,5,6,7])
som = np.sum(num)
men =np.mean(num)
st =np.std(num)
print(som)
print(men)
print(st)



28
4.0
2.0


Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.



In [19]:
import numpy as np
range = np.arange(25)
matrx = range.reshape(5,5)
print(matrx)
maxi = np.max(matrx)
min = np.min(matrx)
print(maxi)
print(min)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
24
0


Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [20]:
import numpy as np
one_d_array = np.array([1, 2, 3, 4, 5])
print(one_d_array)

two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_d_array)

three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(three_d_array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
import numpy as np

# Specify the dimensions of the 2D array
rows, cols = 5, 5

# Create a 2D array filled with zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Set the top row to 1
array[-1, :] = 1  # Set the bottom row to 1
array[:, 0] = 1  # Set the leftmost column to 1
array[:, -1] = 1  # Set the rightmost column to 1
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
